blueprint:
  name: LSG - Alert on Stale Entities
  description: Send notification when entities become stale (offline/unresponsive)
  domain: automation
  input:
    notify_service:
      name: Notification Service
      description: The notify service to use
      default: notify.notify
      selector:
        text:
    
    min_stale_count:
      name: Minimum Stale Count
      description: Only alert if at least this many entities are stale
      default: 1
      selector:
        number:
          min: 1
          max: 50
          mode: box
    
    throttle_minutes:
      name: Throttle Time
      description: Minimum minutes between alerts
      default: 30
      selector:
        number:
          min: 5
          max: 1440
          mode: box

trigger:
  - platform: state
    entity_id: sensor.lsg_stale_entities
    
condition:
  - condition: template
    value_template: >
      {{ states('sensor.lsg_stale_entities') | int >= min_stale_count }}

action:
  - service: !input notify_service
    data:
      title: "🚨 LSG Alert: Entities Not Responding"
      message: >
        {{ states('sensor.lsg_stale_entities') }} entities are stale.
        
        Failed entities:
        {{ state_attr('sensor.lsg_failed_entities', 'entity_ids') | join('\n') }}
        
        Check the Last Seen Guardian panel for details.
      data:
        priority: high
        tag: lsg_stale_alert
        actions:
          - action: URI
            title: "Open LSG Panel"
            uri: "/last_seen_guardian"

mode: single