blueprint:
  name: LSG - Battery Monitor Alert
  description: Alert when entities with low battery are detected in LSG diagnostics
  domain: automation
  input:
    notify_service:
      name: Notification Service
      description: The notify service to use
      default: notify.notify
      selector:
        text:
    
    battery_threshold:
      name: Battery Threshold
      description: Alert when battery drops below this percentage
      default: 20
      selector:
        number:
          min: 5
          max: 50
          mode: slider
          unit_of_measurement: "%"

trigger:
  - platform: time_pattern
    minutes: "/30"

condition: []

action:
  # Call LSG service to export diagnostics
  - service: last_seen_guardian.export_diagnostics
    response_variable: diagnostics_data
  
  # Check entities with low battery in technical context
  - variables:
      low_battery_entities: >
        {% set ns = namespace(entities=[]) %}
        {% for entity in diagnostics_data.diagnostics.entities %}
          {% if entity.stats.technical_context.battery_level is defined %}
            {% if entity.stats.technical_context.battery_level < battery_threshold %}
              {% set ns.entities = ns.entities + [entity.entity_id ~ ' (' ~ entity.stats.technical_context.battery_level ~ '%)'] %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ ns.entities }}
  
  # Send notification if any found
  - condition: template
    value_template: "{{ low_battery_entities | length > 0 }}"
  
  - service: !input notify_service
    data:
      title: "🔋 LSG: Low Battery Alert"
      message: >
        {{ low_battery_entities | length }} device(s) have low battery:
        
        {{ low_battery_entities | join('\n') }}
      data:
        priority: normal
        tag: lsg_battery_alert

mode: single